# Generated by Django 6.0.5 on 2026-05-21 13:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventoryreservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryreservation",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="reservation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
