# Generated by Django 6.0.5 on 2026-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_brand_deleted_at_brand_is_deleted_and_more"),
        ("inventory", "0003_inventoryreservation_confirmed_and_more"),
        ("orders", "0006_address_deleted_at_address_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["created_at"], name="inventory_i_created_4ce036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["expires_at"], name="inventory_i_expires_858ce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["released"], name="inventory_i_release_9d8a99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["created_at"], name="inventory_i_created_305a56_idx"
            ),
        ),
    ]
