# Generated by Django 6.0.5 on 2026-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_brand_deleted_at_brand_is_deleted_and_more"),
        ("inventory", "0005_inventorymovement"),
        ("orders", "0006_address_deleted_at_address_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="inventoryreservation",
            name="inventory_i_release_9d8a99_idx",
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("consumed", "Consumed"),
                    ("released", "Released"),
                    ("expired", "Expired"),
                ],
                default="active",
                help_text="Current reservation lifecycle state.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="expires_at",
            field=models.DateTimeField(help_text="Reservation expiration timestamp."),
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Reserved quantity for this reservation."
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(fields=["status"], name="inventory_i_status_e748a8_idx"),
        ),
        migrations.RemoveField(
            model_name="inventoryreservation",
            name="confirmed",
        ),
        migrations.RemoveField(
            model_name="inventoryreservation",
            name="released",
        ),
    ]
