# Generated by Django 6.0.5 on 2026-05-21 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_status_orderevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="address",
            name="is_billing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="is_shipping",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="address",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
