# Generated by Django 6.0.5 on 2026-05-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_catalog_cat_slug_695af4_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-is_primary", "sort_order", "created_at"]},
        ),
        migrations.AddField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="catalog_pro_product_c9ec4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_187601_idx"),
        ),
    ]
