# Generated by Django 6.0.5 on 2026-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_productimage_options_productimage_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
