# Generated by Django 6.0.5 on 2026-05-21 12:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_webhookevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider",
            field=models.CharField(default="mercadopago", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="request_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="transaction",
            name="response_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="transaction",
            name="success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
