name: Backend Security

on:
  schedule:
    - cron: "0 5 * * 1"

  workflow_dispatch:

jobs:

  security:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install uv

      - run: uv sync

      - run: uv run pip-audit
